language: ruby
sudo: false
cache: bundler

services:
  - redis

before_install:
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"

script: bundle exec rake

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
